### ISSUE TITLE
Setup initial input into generate.py

### ISSUE THREAD

**Issue by sihsob** [samanthajlee2/ExistentialGraphProofGenerator#1]
Using generate.py as the general script, create a command line interface to provide a place to put in the necessary files that contain the premises and goal of the proof.  Right now it just takes in user input

**Comment by samanthajlee2** [comment]
https://github.com/samanthajlee2/ExistentialGraphProofGenerator/commit/892d3a3674681f59a0ee87d755dac335e28e55a9
