### ISSUE TITLE
Handle multiple premises in addition to just one line

### ISSUE THREAD

**Issue by sihsob** [samanthajlee2/ExistentialGraphProofGenerator#7]
Currently takes in input from terminal in a single line, but should eventually be able to generate a single existential graph tree from multiple premises for use in automated proof generation.  Should only need some changes in `generate.py` and potentially `existential_statement.py`

**Comment by sihsob** [comment]
@samanthajlee2 Is this completed?

**Comment by samanthajlee2** [comment]
yeah should be
